Fix KeyError
naveen521kk/sxcu pull request #10
Opened 2020-10-08 18:30 UTC by shahprog

If a .sxcu file don't have `Arguments`  which causes a KeyError.

2020-10-09 06:43 UTC, naveen521kk commented
Thank you for your PR.

Can you pull the master branch so that it runs test? Also, is it possible to add a small test? If not possible, I will do ;-)

2020-10-09 10:07 UTC, naveen521kk requested changes

2020-10-09 10:07 UTC, naveen521kk commented on sxcu/sxcu.py
> +            if "Arguments" in con.keys():
This is lot better.
```suggestion
            if "Arguments" in con:
```

2020-10-09 13:10 UTC, naveen521kk approved these changes
LGTM! I will do a follow up on tests.

2020-10-09 13:11 UTC, merged

2020-10-09 22:06 UTC, shahprog commented
Also it has some more issue. I was making an GUI for uploading jn sxcu and the lib was doing some problem. Then i need to fix them in the source to make that GUI executable work. Some code in the __init__ ar causing the tkinter GUI to fail run the script.

2020-10-10 03:19 UTC, naveen521kk commented
Do you mean this
https://github.com/naveen521kk/sxcu/blob/master/sxcu/__init__.py#L11-L18

> Some code in the init are causing the tkinter GUI to fail run the script.

Could you exactly say what is the issue?

2020-10-11 10:27 UTC, shahprog commented
```py
 try: 
     from importlib.metadata import version as importlib_metadata_version 
 except ImportError: 
     from importlib_metadata import version as importlib_metadata_version 
  
 __version__ = importlib_metadata_version("sxcu") 
```

Removing these line solved the issue Somehow it caused an error when I use pyinstaller to make a onefile

2020-10-11 10:38 UTC, naveen521kk commented
It doesn't hurt for me to remove it. What it does gets the version and sets to the variable. It can also be hard coded. I will be happy if you do a PR.

2020-10-13 19:17 UTC, naveen521kk commented
@shahprog I removed it in https://github.com/naveen521kk/sxcu/commit/447b2d9296ff6c75c07836c4f545b44d96a81748
I will do a release tomorrow and then you can use it.

2020-10-16 18:53 UTC, naveen521kk commented
@all-contributors please add @shahprog for bug, code